# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  enable:
    - goconst
    - gocritic
    - govet
    - gosec
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - hack
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - hack
      - third_party$
      - builtin$
      - examples$
