name: ketall CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go 1.23.2
        uses: actions/setup-go@v5
        id: go
        with:
          go-version: 1.23.2
      - name: Verify go.mod is sane
        run: go mod tidy && git diff --no-patch --exit-code
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
      - name: Run unit tests
        run: go test ./...
      - name: GoReleaser Build Snapshot
        if: "!contains(github.ref, 'tags')"
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: GoReleaser Release
        if: contains(github.ref, 'tags')
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update new version in krew-index
        if: contains(github.ref, 'tags')
        uses: rajatjindal/krew-release-bot@v0.0.47
        with:
          krew_template_file: .krew.yaml
