name: ketall CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.23.2
      uses: actions/setup-go@v5
      id: go
      with:
        go-version: 1.23.2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Verify go.mod is sane
      run: go mod tidy && git diff --no-patch --exit-code

    - name: Run code lint
      run: make lint

    - name: Install dependencies
      run: go mod download

    - name: Run unit tests
      run: |
        set -euo pipefail
        make test
        make coverage

    - uses: codecov/codecov-action@v4
      name: Upload coverage to codecov.io
      if: "${{ env.SECRET_CODECOV_TOKEN != '' }}"
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./out/coverage.txt

    - name: GoReleaser Build Snapshot
      if: "!contains(github.ref, 'tags')"
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --snapshot --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: GoReleaser Release
      if: contains(github.ref, 'tags')
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update new version in krew-index
      if: contains(github.ref, 'tags')
      uses: rajatjindal/krew-release-bot@v0.0.39
      with:
        krew_template_file: hack/get-all.yaml
